stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: flora/api
  DOCKER_TAG: $CI_COMMIT_SHA

test:
  stage: test
  image: python:3.11
  script:
    - cd flora/api
    - pip install -r requirements.txt
    - cd ../security
    - python run_tests.py --target-url http://localhost:8000
    - python test_api_simple.py
  only:
    - main
    - develop

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - kubectl apply -f k8s/
  only:
    - main
